### ISSUE TITLE
Running and nothing happened?

### ISSUE THREAD

**Issue by mylovesaber** [userdocs/python-libtorrent-binding#3]
```bash
root@Ubuntu-2004-focal-64-minimal ~ # ~/libtorrent-python-binding.sh  pv 2 -lt libtorrent-1_1_14

Libtorrent tag libtorrent-1_1_14 verified!
root@Ubuntu-2004-focal-64-minimal ~ 
```
No ~/libtorrent-python/completed created. The whole process only lasts a few seconds.

**Comment by userdocs** [comment]
Well, with a name like that...

Assuming you have fixed the boost issue and you are using 1.76.0 as 1.77.0 will not work you are doing 2 things wrong.

```
~/libtorrent-python-binding.sh all -pv 2 -lt libtorrent-1_1_14
```

**Comment by mylovesaber** [comment]
I reinstalled the server and did the test. Here is the log:
```
root@Ubuntu-2004-focal-64-minimal ~/libtorrent-python/completed # ls
libtorrent.so
root@Ubuntu-2004-focal-64-minimal ~/libtorrent-python/completed # ~/libtorrent-python-binding.sh install

Checking if required core dependencies are installed

Dependency - OK - bison
Dependency - OK - curl
Dependency - OK - build-essential
Dependency - OK - pkg-config
Dependency - OK - automake
Dependency - OK - libtool
Dependency - OK - git
Dependency - OK - perl
Dependency - OK - python3
Dependency - OK - python3-dev
Dependency - OK - python3-numpy
Dependency - OK - python3-pip

Install Prefix : /root/libtorrent-python

Script help : ~/libtorrent-python-binding.sh -h
Collecting deluge
  Downloading deluge-2.0.3-py3-none-any.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 10.3 MB/s 
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from deluge) (1.14.0)
Collecting pyxdg
  Downloading pyxdg-0.27-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 7.7 MB/s 
Collecting rencode
  Downloading rencode-1.0.6.tar.gz (74 kB)
     |████████████████████████████████| 74 kB 2.9 MB/s 
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from deluge) (3.0.4)
Collecting pillow
  Downloading Pillow-8.4.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 109.0 MB/s 
Collecting pyopenssl
  Downloading pyOpenSSL-21.0.0-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 3.8 MB/s 
Collecting zope.interface
  Downloading zope.interface-5.4.0-cp38-cp38-manylinux2010_x86_64.whl (259 kB)
     |████████████████████████████████| 259 kB 105.6 MB/s 
Collecting pyasn1
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     |████████████████████████████████| 77 kB 7.3 MB/s 
Collecting mako
  Downloading Mako-1.1.5-py2.py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 5.2 MB/s 
Collecting twisted[tls]>=17.1
  Downloading Twisted-21.7.0-py3-none-any.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 111.6 MB/s 
Collecting setproctitle
  Downloading setproctitle-1.2.2-cp38-cp38-manylinux1_x86_64.whl (36 kB)
Collecting cryptography>=3.3
  Downloading cryptography-35.0.0-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 113.0 MB/s 
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from zope.interface->deluge) (45.2.0)
Collecting MarkupSafe>=0.9.2
  Downloading MarkupSafe-2.0.1-cp38-cp38-manylinux2010_x86_64.whl (30 kB)
Collecting Automat>=0.8.0
  Downloading Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting constantly>=15.1
  Downloading constantly-15.1.0-py2.py3-none-any.whl (7.9 kB)
Collecting attrs>=19.2.0
  Downloading attrs-21.2.0-py2.py3-none-any.whl (53 kB)
     |████████████████████████████████| 53 kB 2.8 MB/s 
Collecting incremental>=21.3.0
  Downloading incremental-21.3.0-py2.py3-none-any.whl (15 kB)
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting hyperlink>=17.1.1
  Downloading hyperlink-21.0.0-py2.py3-none-any.whl (74 kB)
     |████████████████████████████████| 74 kB 4.2 MB/s 
Collecting idna>=2.4; extra == "tls"
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 8.8 MB/s 
Collecting service-identity>=18.1.0; extra == "tls"
  Downloading service_identity-21.1.0-py2.py3-none-any.whl (12 kB)
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
     |████████████████████████████████| 446 kB 114.9 MB/s 
Collecting pyasn1-modules
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     |████████████████████████████████| 155 kB 116.0 MB/s 
Collecting pycparser
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 111.7 MB/s 
Building wheels for collected packages: rencode
  Building wheel for rencode (setup.py) ... done
  Created wheel for rencode: filename=rencode-1.0.6-cp38-cp38-linux_x86_64.whl size=248756 sha256=f85daa3f0217c072d5fbfc125bda81d4dfd565d04c0df3a56fe869f56860a956
  Stored in directory: /root/.cache/pip/wheels/d9/3c/6a/4497b64ba1a685a165f18fa315846b74c3230bba1d1fc6a033
Successfully built rencode
Installing collected packages: pyxdg, rencode, pillow, pycparser, cffi, cryptography, pyopenssl, zope.interface, pyasn1, MarkupSafe, mako, attrs, Automat, constantly, incremental, typing-extensions, idna, hyperlink, pyasn1-modules, service-identity, twisted, setproctitle, deluge
  WARNING: The script mako-render is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script automat-visualize is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts cftp, ckeygen, conch, mailmail, pyhtmlizer, tkconch, trial, twist and twistd are installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts deluge-console, deluge-web and deluged are installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Automat-20.2.0 MarkupSafe-2.0.1 attrs-21.2.0 cffi-1.15.0 constantly-15.1.0 cryptography-35.0.0 deluge-2.0.3 hyperlink-21.0.0 idna-3.3 incremental-21.3.0 mako-1.1.5 pillow-8.4.0 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycparser-2.20 pyopenssl-21.0.0 pyxdg-0.27 rencode-1.0.6 service-identity-21.1.0 setproctitle-1.2.2 twisted-21.7.0 typing-extensions-3.10.0.2 zope.interface-5.4.0
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/deluge/_libtorrent.py", line 23, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/deluged", line 8, in <module>
    sys.exit(start_daemon())
  File "/root/.local/lib/python3.8/site-packages/deluge/core/daemon_entry.py", line 90, in start_daemon
    from deluge.core.daemon import is_daemon_running
  File "/root/.local/lib/python3.8/site-packages/deluge/core/daemon.py", line 22, in <module>
    from deluge.core.core import Core
  File "/root/.local/lib/python3.8/site-packages/deluge/core/core.py", line 28, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/root/.local/lib/python3.8/site-packages/deluge/_libtorrent.py", line 25, in <module>
    import libtorrent as lt
ModuleNotFoundError: No module named 'libtorrent'
Unable to initialize gettext/locale!
'ngettext'
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation
    builtins.__dict__['_n'] = builtins.__dict__['ngettext']
KeyError: 'ngettext'
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/deluge/_libtorrent.py", line 23, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/deluge-console", line 8, in <module>
    sys.exit(start())
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/__init__.py", line 19, in start
    Console().start()
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/console.py", line 154, in start
    from deluge.ui.console.main import ConsoleUI  # import here because (see top)
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/main.py", line 27, in <module>
    from deluge.ui.console.modes.addtorrents import AddTorrents
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/modes/addtorrents.py", line 21, in <module>
    from deluge.ui.console.modes.torrentlist.add_torrents_popup import report_add_status
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/modes/torrentlist/add_torrents_popup.py", line 16, in <module>
    from deluge.ui.console.widgets.popup import InputPopup, SelectablePopup
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/widgets/__init__.py", line 4, in <module>
    from deluge.ui.console.widgets.statusbars import StatusBars
  File "/root/.local/lib/python3.8/site-packages/deluge/ui/console/widgets/statusbars.py", line 14, in <module>
    from deluge.core.preferencesmanager import DEFAULT_PREFS
  File "/root/.local/lib/python3.8/site-packages/deluge/core/preferencesmanager.py", line 24, in <module>
    from deluge._libtorrent import lt
  File "/root/.local/lib/python3.8/site-packages/deluge/_libtorrent.py", line 25, in <module>
    import libtorrent as lt
ModuleNotFoundError: No module named 'libtorrent'
```

**Comment by userdocs** [comment]
These are not the same commands? It's two totally different steps?

I pushed these to fix building https://github.com/userdocs/python-libtorrent-binding/commit/eab2a9e6c8c249e727c143ae6c6a786335fed448

Is that part fixed now? i need to test the install bit now?

**Comment by mylovesaber** [comment]
After a fresh system installation and with the following command:
```bash
wget -qO ~/libtorrent-python-binding.sh https://git.io/gplibtorrent
chmod 700 ~/libtorrent-python-binding.sh
~/libtorrent-python-binding.sh
reboot
~/libtorrent-python-binding.sh
~/libtorrent-python-binding.sh all pv 2 -lt libtorrent-1_1_14
```
It go back to the first problem...
```
root@Ubuntu-2004-focal-64-minimal ~ # ~/libtorrent-python-binding.sh all pv 2 -lt libtorrent-1_1_14

Libtorrent tag libtorrent-1_1_14 verified!

Checking if required core dependencies are installed

Dependency - OK - bison
Dependency - OK - curl
Dependency - OK - build-essential
Dependency - OK - pkg-config
Dependency - OK - automake
Dependency - OK - libtool
Dependency - OK - git
Dependency - OK - perl
Dependency - OK - python3
Dependency - OK - python3-dev
Dependency - OK - python3-numpy
Dependency - OK - python3-pip

One or more of the provided modules are not supported

This is a list of supported modules

all install openssl boost libtorrent
```

**Comment by mylovesaber** [comment]
Would you want a server with a few days left? You can work on it~~

**Comment by userdocs** [comment]
you want to install deluge 2? with python 2?

Why not use deluge 2 with python 3? 

Ubuntu focal has no python 2 pip to install unless you do it manually.

**Comment by userdocs** [comment]
Please see https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/

**Comment by userdocs** [comment]
Ok, i made a tweak so if you have pip2 it will use it. but I recommend you just stick with python 3 unless you really need python 2.
